---
name: Data-Pageset-Render
version: 0.14
author:
  - 'Mark Grimes, E<lt>mgrimes@cpan.orgE<gt>'
abstract: |-
  Subclass of C<Data::Pageset> that generates html, text,
  etc. for page navigation
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Data::Pageset: 1.04
provides:
  Data::Pageset::Render:
    file: lib/Data/Pageset/Render.pm
    version: 0.14
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
